with-expecter: 'true'
dir: mocks/{{replace .InterfaceDirRelative "internal" "" 1}}
unroll-variadic: 'false'
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
filename: "mock_{{.InterfaceName|lower}}.go"
packages:
  github.com/castai/dbo-deployment-wizard/internal/backend:
    interfaces:
      Kubectl:
      HelmRunner:
