template: testify
dir: mocks/{{trimPrefix "internal/" .InterfaceDirRelative}}
filename: mock_{{.InterfaceName|lower}}.go
packages:
  github.com/castai/dbo-deployment-wizard/internal/backend:
    interfaces:
      Kubectl: {}
      KubectlShell: {}
      HelmRunner: {}
