// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package backend

import (
	"context"
	"io"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKubectl creates a new instance of MockKubectl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKubectl(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKubectl {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockKubectl{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockKubectl is an autogenerated mock type for the Kubectl type
type MockKubectl struct {
	mock.Mock
}

type MockKubectl_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKubectl) EXPECT() *MockKubectl_Expecter {
	return &MockKubectl_Expecter{mock: &_m.Mock}
}

// CurrentKubeContext provides a mock function for the type MockKubectl
func (_mock *MockKubectl) CurrentKubeContext(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentKubeContext")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKubectl_CurrentKubeContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentKubeContext'
type MockKubectl_CurrentKubeContext_Call struct {
	*mock.Call
}

// CurrentKubeContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKubectl_Expecter) CurrentKubeContext(ctx any) *MockKubectl_CurrentKubeContext_Call {
	return &MockKubectl_CurrentKubeContext_Call{Call: _e.mock.On("CurrentKubeContext", ctx)}
}

func (_c *MockKubectl_CurrentKubeContext_Call) Run(run func(ctx context.Context)) *MockKubectl_CurrentKubeContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKubectl_CurrentKubeContext_Call) Return(s string, err error) *MockKubectl_CurrentKubeContext_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockKubectl_CurrentKubeContext_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockKubectl_CurrentKubeContext_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureSecret provides a mock function for the type MockKubectl
func (_mock *MockKubectl) EnsureSecret(ctx context.Context, kubeContext string, namespace string, name string, data map[string]string, stdout io.Writer, dryRun bool) error {
	ret := _mock.Called(ctx, kubeContext, namespace, name, data, stdout, dryRun)

	if len(ret) == 0 {
		panic("no return value specified for EnsureSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]string, io.Writer, bool) error); ok {
		r0 = returnFunc(ctx, kubeContext, namespace, name, data, stdout, dryRun)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKubectl_EnsureSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureSecret'
type MockKubectl_EnsureSecret_Call struct {
	*mock.Call
}

// EnsureSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - kubeContext string
//   - namespace string
//   - name string
//   - data map[string]string
//   - stdout io.Writer
//   - dryRun bool
func (_e *MockKubectl_Expecter) EnsureSecret(ctx any, kubeContext any, namespace any, name any, data any, stdout any, dryRun any) *MockKubectl_EnsureSecret_Call {
	return &MockKubectl_EnsureSecret_Call{Call: _e.mock.On("EnsureSecret", ctx, kubeContext, namespace, name, data, stdout, dryRun)}
}

func (_c *MockKubectl_EnsureSecret_Call) Run(run func(ctx context.Context, kubeContext string, namespace string, name string, data map[string]string, stdout io.Writer, dryRun bool)) *MockKubectl_EnsureSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]string
		if args[4] != nil {
			arg4 = args[4].(map[string]string)
		}
		var arg5 io.Writer
		if args[5] != nil {
			arg5 = args[5].(io.Writer)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockKubectl_EnsureSecret_Call) Return(err error) *MockKubectl_EnsureSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKubectl_EnsureSecret_Call) RunAndReturn(run func(ctx context.Context, kubeContext string, namespace string, name string, data map[string]string, stdout io.Writer, dryRun bool) error) *MockKubectl_EnsureSecret_Call {
	_c.Call.Return(run)
	return _c
}

// HelmReleaseExists provides a mock function for the type MockKubectl
func (_mock *MockKubectl) HelmReleaseExists(ctx context.Context, kubeContext string, namespace string, releaseName string) (bool, error) {
	ret := _mock.Called(ctx, kubeContext, namespace, releaseName)

	if len(ret) == 0 {
		panic("no return value specified for HelmReleaseExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, kubeContext, namespace, releaseName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, kubeContext, namespace, releaseName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, kubeContext, namespace, releaseName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKubectl_HelmReleaseExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HelmReleaseExists'
type MockKubectl_HelmReleaseExists_Call struct {
	*mock.Call
}

// HelmReleaseExists is a helper method to define mock.On call
//   - ctx context.Context
//   - kubeContext string
//   - namespace string
//   - releaseName string
func (_e *MockKubectl_Expecter) HelmReleaseExists(ctx any, kubeContext any, namespace any, releaseName any) *MockKubectl_HelmReleaseExists_Call {
	return &MockKubectl_HelmReleaseExists_Call{Call: _e.mock.On("HelmReleaseExists", ctx, kubeContext, namespace, releaseName)}
}

func (_c *MockKubectl_HelmReleaseExists_Call) Run(run func(ctx context.Context, kubeContext string, namespace string, releaseName string)) *MockKubectl_HelmReleaseExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKubectl_HelmReleaseExists_Call) Return(b bool, err error) *MockKubectl_HelmReleaseExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockKubectl_HelmReleaseExists_Call) RunAndReturn(run func(ctx context.Context, kubeContext string, namespace string, releaseName string) (bool, error)) *MockKubectl_HelmReleaseExists_Call {
	_c.Call.Return(run)
	return _c
}

// ListKubeContexts provides a mock function for the type MockKubectl
func (_mock *MockKubectl) ListKubeContexts(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListKubeContexts")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKubectl_ListKubeContexts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKubeContexts'
type MockKubectl_ListKubeContexts_Call struct {
	*mock.Call
}

// ListKubeContexts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKubectl_Expecter) ListKubeContexts(ctx any) *MockKubectl_ListKubeContexts_Call {
	return &MockKubectl_ListKubeContexts_Call{Call: _e.mock.On("ListKubeContexts", ctx)}
}

func (_c *MockKubectl_ListKubeContexts_Call) Run(run func(ctx context.Context)) *MockKubectl_ListKubeContexts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKubectl_ListKubeContexts_Call) Return(strings []string, err error) *MockKubectl_ListKubeContexts_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockKubectl_ListKubeContexts_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockKubectl_ListKubeContexts_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function for the type MockKubectl
func (_mock *MockKubectl) ListSecrets(ctx context.Context, kubeContext string, namespace string) ([]string, error) {
	ret := _mock.Called(ctx, kubeContext, namespace)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, kubeContext, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, kubeContext, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, kubeContext, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKubectl_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockKubectl_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - kubeContext string
//   - namespace string
func (_e *MockKubectl_Expecter) ListSecrets(ctx any, kubeContext any, namespace any) *MockKubectl_ListSecrets_Call {
	return &MockKubectl_ListSecrets_Call{Call: _e.mock.On("ListSecrets", ctx, kubeContext, namespace)}
}

func (_c *MockKubectl_ListSecrets_Call) Run(run func(ctx context.Context, kubeContext string, namespace string)) *MockKubectl_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKubectl_ListSecrets_Call) Return(strings []string, err error) *MockKubectl_ListSecrets_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockKubectl_ListSecrets_Call) RunAndReturn(run func(ctx context.Context, kubeContext string, namespace string) ([]string, error)) *MockKubectl_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// RolloutStatus provides a mock function for the type MockKubectl
func (_mock *MockKubectl) RolloutStatus(ctx context.Context, kubeContext string, namespace string, deployment string, timeout time.Duration, stdout io.Writer, stderr io.Writer) error {
	ret := _mock.Called(ctx, kubeContext, namespace, deployment, timeout, stdout, stderr)

	if len(ret) == 0 {
		panic("no return value specified for RolloutStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration, io.Writer, io.Writer) error); ok {
		r0 = returnFunc(ctx, kubeContext, namespace, deployment, timeout, stdout, stderr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKubectl_RolloutStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RolloutStatus'
type MockKubectl_RolloutStatus_Call struct {
	*mock.Call
}

// RolloutStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - kubeContext string
//   - namespace string
//   - deployment string
//   - timeout time.Duration
//   - stdout io.Writer
//   - stderr io.Writer
func (_e *MockKubectl_Expecter) RolloutStatus(ctx any, kubeContext any, namespace any, deployment any, timeout any, stdout any, stderr any) *MockKubectl_RolloutStatus_Call {
	return &MockKubectl_RolloutStatus_Call{Call: _e.mock.On("RolloutStatus", ctx, kubeContext, namespace, deployment, timeout, stdout, stderr)}
}

func (_c *MockKubectl_RolloutStatus_Call) Run(run func(ctx context.Context, kubeContext string, namespace string, deployment string, timeout time.Duration, stdout io.Writer, stderr io.Writer)) *MockKubectl_RolloutStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		var arg5 io.Writer
		if args[5] != nil {
			arg5 = args[5].(io.Writer)
		}
		var arg6 io.Writer
		if args[6] != nil {
			arg6 = args[6].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockKubectl_RolloutStatus_Call) Return(err error) *MockKubectl_RolloutStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKubectl_RolloutStatus_Call) RunAndReturn(run func(ctx context.Context, kubeContext string, namespace string, deployment string, timeout time.Duration, stdout io.Writer, stderr io.Writer) error) *MockKubectl_RolloutStatus_Call {
	_c.Call.Return(run)
	return _c
}
