// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package backend

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKubectlShell creates a new instance of MockKubectlShell. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKubectlShell(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKubectlShell {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockKubectlShell{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockKubectlShell is an autogenerated mock type for the KubectlShell type
type MockKubectlShell struct {
	mock.Mock
}

type MockKubectlShell_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKubectlShell) EXPECT() *MockKubectlShell_Expecter {
	return &MockKubectlShell_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockKubectlShell
func (_mock *MockKubectlShell) Run(ctx context.Context, args ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, args)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]byte, error)); ok {
		return returnFunc(ctx, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []byte); ok {
		r0 = returnFunc(ctx, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKubectlShell_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockKubectlShell_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - args ...string
func (_e *MockKubectlShell_Expecter) Run(ctx any, args ...any) *MockKubectlShell_Run_Call {
	return &MockKubectlShell_Run_Call{Call: _e.mock.On("Run",
		append([]any{ctx}, args...)...)}
}

func (_c *MockKubectlShell_Run_Call) Run(run func(ctx context.Context, args ...string)) *MockKubectlShell_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockKubectlShell_Run_Call) Return(bytes []byte, err error) *MockKubectlShell_Run_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKubectlShell_Run_Call) RunAndReturn(run func(ctx context.Context, args ...string) ([]byte, error)) *MockKubectlShell_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunInput provides a mock function for the type MockKubectlShell
func (_mock *MockKubectlShell) RunInput(ctx context.Context, stdin []byte, args ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, stdin, args)
	} else {
		tmpRet = _mock.Called(ctx, stdin)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RunInput")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, ...string) ([]byte, error)); ok {
		return returnFunc(ctx, stdin, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, ...string) []byte); ok {
		r0 = returnFunc(ctx, stdin, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, ...string) error); ok {
		r1 = returnFunc(ctx, stdin, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKubectlShell_RunInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInput'
type MockKubectlShell_RunInput_Call struct {
	*mock.Call
}

// RunInput is a helper method to define mock.On call
//   - ctx context.Context
//   - stdin []byte
//   - args ...string
func (_e *MockKubectlShell_Expecter) RunInput(ctx any, stdin any, args ...any) *MockKubectlShell_RunInput_Call {
	return &MockKubectlShell_RunInput_Call{Call: _e.mock.On("RunInput",
		append([]any{ctx, stdin}, args...)...)}
}

func (_c *MockKubectlShell_RunInput_Call) Run(run func(ctx context.Context, stdin []byte, args ...string)) *MockKubectlShell_RunInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockKubectlShell_RunInput_Call) Return(bytes []byte, err error) *MockKubectlShell_RunInput_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKubectlShell_RunInput_Call) RunAndReturn(run func(ctx context.Context, stdin []byte, args ...string) ([]byte, error)) *MockKubectlShell_RunInput_Call {
	_c.Call.Return(run)
	return _c
}
