// Code generated by mockery. DO NOT EDIT.

package backend

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockHelmRunner is an autogenerated mock type for the HelmRunner type
type MockHelmRunner struct {
	mock.Mock
}

type MockHelmRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelmRunner) EXPECT() *MockHelmRunner_Expecter {
	return &MockHelmRunner_Expecter{mock: &_m.Mock}
}

// Argv provides a mock function with given fields: argv
func (_m *MockHelmRunner) Argv(argv []string) []string {
	ret := _m.Called(argv)

	if len(ret) == 0 {
		panic("no return value specified for Argv")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func([]string) []string); ok {
		r0 = rf(argv)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockHelmRunner_Argv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Argv'
type MockHelmRunner_Argv_Call struct {
	*mock.Call
}

// Argv is a helper method to define mock.On call
//   - argv []string
func (_e *MockHelmRunner_Expecter) Argv(argv interface{}) *MockHelmRunner_Argv_Call {
	return &MockHelmRunner_Argv_Call{Call: _e.mock.On("Argv", argv)}
}

func (_c *MockHelmRunner_Argv_Call) Run(run func(argv []string)) *MockHelmRunner_Argv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockHelmRunner_Argv_Call) Return(_a0 []string) *MockHelmRunner_Argv_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHelmRunner_Argv_Call) RunAndReturn(run func([]string) []string) *MockHelmRunner_Argv_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx, argv, stdout, stderr
func (_m *MockHelmRunner) Run(ctx context.Context, argv []string, stdout io.Writer, stderr io.Writer) error {
	ret := _m.Called(ctx, argv, stdout, stderr)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, io.Writer, io.Writer) error); ok {
		r0 = rf(ctx, argv, stdout, stderr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHelmRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockHelmRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - argv []string
//   - stdout io.Writer
//   - stderr io.Writer
func (_e *MockHelmRunner_Expecter) Run(ctx interface{}, argv interface{}, stdout interface{}, stderr interface{}) *MockHelmRunner_Run_Call {
	return &MockHelmRunner_Run_Call{Call: _e.mock.On("Run", ctx, argv, stdout, stderr)}
}

func (_c *MockHelmRunner_Run_Call) Run(run func(ctx context.Context, argv []string, stdout io.Writer, stderr io.Writer)) *MockHelmRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(io.Writer), args[3].(io.Writer))
	})
	return _c
}

func (_c *MockHelmRunner_Run_Call) Return(_a0 error) *MockHelmRunner_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHelmRunner_Run_Call) RunAndReturn(run func(context.Context, []string, io.Writer, io.Writer) error) *MockHelmRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHelmRunner creates a new instance of MockHelmRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelmRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelmRunner {
	mock := &MockHelmRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
