// Code generated by mockery. DO NOT EDIT.

package backend

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockKubectl is an autogenerated mock type for the Kubectl type
type MockKubectl struct {
	mock.Mock
}

type MockKubectl_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKubectl) EXPECT() *MockKubectl_Expecter {
	return &MockKubectl_Expecter{mock: &_m.Mock}
}

// CurrentKubeContext provides a mock function with given fields: ctx
func (_m *MockKubectl) CurrentKubeContext(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentKubeContext")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKubectl_CurrentKubeContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentKubeContext'
type MockKubectl_CurrentKubeContext_Call struct {
	*mock.Call
}

// CurrentKubeContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKubectl_Expecter) CurrentKubeContext(ctx interface{}) *MockKubectl_CurrentKubeContext_Call {
	return &MockKubectl_CurrentKubeContext_Call{Call: _e.mock.On("CurrentKubeContext", ctx)}
}

func (_c *MockKubectl_CurrentKubeContext_Call) Run(run func(ctx context.Context)) *MockKubectl_CurrentKubeContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockKubectl_CurrentKubeContext_Call) Return(_a0 string, _a1 error) *MockKubectl_CurrentKubeContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKubectl_CurrentKubeContext_Call) RunAndReturn(run func(context.Context) (string, error)) *MockKubectl_CurrentKubeContext_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureSecret provides a mock function with given fields: ctx, kubeContext, namespace, name, data
func (_m *MockKubectl) EnsureSecret(ctx context.Context, kubeContext string, namespace string, name string, data map[string]string) error {
	ret := _m.Called(ctx, kubeContext, namespace, name, data)

	if len(ret) == 0 {
		panic("no return value specified for EnsureSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]string) error); ok {
		r0 = rf(ctx, kubeContext, namespace, name, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKubectl_EnsureSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureSecret'
type MockKubectl_EnsureSecret_Call struct {
	*mock.Call
}

// EnsureSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - kubeContext string
//   - namespace string
//   - name string
//   - data map[string]string
func (_e *MockKubectl_Expecter) EnsureSecret(ctx interface{}, kubeContext interface{}, namespace interface{}, name interface{}, data interface{}) *MockKubectl_EnsureSecret_Call {
	return &MockKubectl_EnsureSecret_Call{Call: _e.mock.On("EnsureSecret", ctx, kubeContext, namespace, name, data)}
}

func (_c *MockKubectl_EnsureSecret_Call) Run(run func(ctx context.Context, kubeContext string, namespace string, name string, data map[string]string)) *MockKubectl_EnsureSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(map[string]string))
	})
	return _c
}

func (_c *MockKubectl_EnsureSecret_Call) Return(_a0 error) *MockKubectl_EnsureSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKubectl_EnsureSecret_Call) RunAndReturn(run func(context.Context, string, string, string, map[string]string) error) *MockKubectl_EnsureSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ListKubeContexts provides a mock function with given fields: ctx
func (_m *MockKubectl) ListKubeContexts(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListKubeContexts")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKubectl_ListKubeContexts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKubeContexts'
type MockKubectl_ListKubeContexts_Call struct {
	*mock.Call
}

// ListKubeContexts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKubectl_Expecter) ListKubeContexts(ctx interface{}) *MockKubectl_ListKubeContexts_Call {
	return &MockKubectl_ListKubeContexts_Call{Call: _e.mock.On("ListKubeContexts", ctx)}
}

func (_c *MockKubectl_ListKubeContexts_Call) Run(run func(ctx context.Context)) *MockKubectl_ListKubeContexts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockKubectl_ListKubeContexts_Call) Return(_a0 []string, _a1 error) *MockKubectl_ListKubeContexts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKubectl_ListKubeContexts_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockKubectl_ListKubeContexts_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function with given fields: ctx, kubeContext, namespace
func (_m *MockKubectl) ListSecrets(ctx context.Context, kubeContext string, namespace string) ([]string, error) {
	ret := _m.Called(ctx, kubeContext, namespace)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, kubeContext, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, kubeContext, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, kubeContext, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKubectl_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockKubectl_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - kubeContext string
//   - namespace string
func (_e *MockKubectl_Expecter) ListSecrets(ctx interface{}, kubeContext interface{}, namespace interface{}) *MockKubectl_ListSecrets_Call {
	return &MockKubectl_ListSecrets_Call{Call: _e.mock.On("ListSecrets", ctx, kubeContext, namespace)}
}

func (_c *MockKubectl_ListSecrets_Call) Run(run func(ctx context.Context, kubeContext string, namespace string)) *MockKubectl_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockKubectl_ListSecrets_Call) Return(_a0 []string, _a1 error) *MockKubectl_ListSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKubectl_ListSecrets_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *MockKubectl_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKubectl creates a new instance of MockKubectl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKubectl(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKubectl {
	mock := &MockKubectl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
