// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package backend

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProcessRunner creates a new instance of MockProcessRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessRunner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProcessRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProcessRunner is an autogenerated mock type for the ProcessRunner type
type MockProcessRunner struct {
	mock.Mock
}

type MockProcessRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessRunner) EXPECT() *MockProcessRunner_Expecter {
	return &MockProcessRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockProcessRunner
func (_mock *MockProcessRunner) Run(ctx context.Context, program string, stdin []byte, args []string) ([]byte, error) {
	ret := _mock.Called(ctx, program, stdin, args)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, []string) ([]byte, error)); ok {
		return returnFunc(ctx, program, stdin, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, []string) []byte); ok {
		r0 = returnFunc(ctx, program, stdin, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, []string) error); ok {
		r1 = returnFunc(ctx, program, stdin, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockProcessRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - program string
//   - stdin []byte
//   - args []string
func (_e *MockProcessRunner_Expecter) Run(ctx any, program any, stdin any, args any) *MockProcessRunner_Run_Call {
	return &MockProcessRunner_Run_Call{Call: _e.mock.On("Run", ctx, program, stdin, args)}
}

func (_c *MockProcessRunner_Run_Call) Run(run func(ctx context.Context, program string, stdin []byte, args []string)) *MockProcessRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProcessRunner_Run_Call) Return(bytes []byte, err error) *MockProcessRunner_Run_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProcessRunner_Run_Call) RunAndReturn(run func(ctx context.Context, program string, stdin []byte, args []string) ([]byte, error)) *MockProcessRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunStream provides a mock function for the type MockProcessRunner
func (_mock *MockProcessRunner) RunStream(ctx context.Context, program string, args []string, stdout io.Writer, stderr io.Writer) error {
	ret := _mock.Called(ctx, program, args, stdout, stderr)

	if len(ret) == 0 {
		panic("no return value specified for RunStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, io.Writer, io.Writer) error); ok {
		r0 = returnFunc(ctx, program, args, stdout, stderr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcessRunner_RunStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunStream'
type MockProcessRunner_RunStream_Call struct {
	*mock.Call
}

// RunStream is a helper method to define mock.On call
//   - ctx context.Context
//   - program string
//   - args []string
//   - stdout io.Writer
//   - stderr io.Writer
func (_e *MockProcessRunner_Expecter) RunStream(ctx any, program any, args any, stdout any, stderr any) *MockProcessRunner_RunStream_Call {
	return &MockProcessRunner_RunStream_Call{Call: _e.mock.On("RunStream", ctx, program, args, stdout, stderr)}
}

func (_c *MockProcessRunner_RunStream_Call) Run(run func(ctx context.Context, program string, args []string, stdout io.Writer, stderr io.Writer)) *MockProcessRunner_RunStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 io.Writer
		if args[3] != nil {
			arg3 = args[3].(io.Writer)
		}
		var arg4 io.Writer
		if args[4] != nil {
			arg4 = args[4].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProcessRunner_RunStream_Call) Return(err error) *MockProcessRunner_RunStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcessRunner_RunStream_Call) RunAndReturn(run func(ctx context.Context, program string, args []string, stdout io.Writer, stderr io.Writer) error) *MockProcessRunner_RunStream_Call {
	_c.Call.Return(run)
	return _c
}
